export const TYPEORM_HOST = 'TYPEORM_HOST';
export const TYPEORM_PORT = 'TYPEORM_PORT';
export const TYPEORM_USERNAME = 'TYPEORM_USERNAME';
export const TYPEORM_PASSWORD = 'TYPEORM_PASSWORD';
export const TYPEORM_DATABASE = 'TYPEORM_DATABASE';
export const TYPEORM_SYNCHRONIZE = 'TYPEORM_SYNCHRONIZE';
